In [308]:
import pandas as pd
import numpy as np
import datetime
import urllib.request 
import json

##Read CSV into pandas as a data frame to be more easily manipulated in python
data = pd.read_csv("~/Desktop/mortality_data_CDC.csv", low_memory = False, nrows = 1000)
##This mortality dataset comes from CDC data and contains
##suicide information between the years 2010-2015.

#Include link in comments
data.head()
#list(data.columns)

,resident_status,education_1989_revision,education_2003_revision,education_reporting_flag,month_of_death,sex,detail_age_type,detail_age,age_recode_52,age_recode_27,age_recode_12,marital_status,day_of_week_of_death,current_data_year,manner_of_death,race_recode_5,hispanic_origin_race_recode
0,2,12,NaN,0,1,F,1,68,39,19,9,D,6,2010,7,3,8
1,1,6,NaN,0,1,F,1,12,28,8,3,S,1,2010,7,1,6
2,1,12,NaN,0,1,F,1,75,41,21,10,D,1,2010,7,1,6
3,1,12,NaN,0,1,M,1,61,38,18,8,W,6,2010,7,4,8
4,1,14,NaN,0,1,F,1,46,35,15,7,M,7,2010,2,1,6

In [309]:
data["suicide_flag"] = data.manner_of_death.apply(lambda row_entry: 1 if row_entry == 2.0 else 0)


col_list = ["month_of_death", "sex", "marital_status", "day_of_week_of_death", 
           "suicide_flag", "education_2003_revision", "race_recode_5",
           "hispanic_origin_race_recode", "age_recode_27"]
data = data[col_list]

data = data.loc[:100]
#data.head()

In [310]:

feature_list = ["month_of_death", "sex", "age_recode_27", "marital_status", 
                "day_of_week_of_death","race_recode_5", "hispanic_origin_race_recode", 
                "suicide_flag", "education_2003_revision"]

input_feature_list = data[feature_list]

input_feature_list.columns = ["current month", "sex", "age", "marital status",
                              "day of the week", "race", "hispanic origin", "suicide flag",
                              "education"]

feature_question_list = []

for feature in input_feature_list.columns:
    if feature == "day of the week" or feature == "current month":
        feature_question = "What's the {}?".format(feature)
    else:
        feature_question = "What's your {}?".format(feature)
    feature_question_list.append(feature_question)

    
    
age_group_options = [
"Under 1 month",
"1 month - 11 months", "1 year", "2 years", "3 years", "4 years", "5  - 9  years",
"10 - 14 years", "15 - 19 years", "20 - 24 years", "25 - 29 years", "30 - 34 years",
"35 - 39 years", "40 - 44 years", "45 - 49 years", "50 - 54 years", "55 - 59 years",
"60 - 64 years", "65 - 69 years", "70 - 74 years", "75 - 79 years", "80 - 84 years",
"85 - 89 years", "90 - 94 years", "95 - 99 years"]
age_group_code = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
20, 21, 22, 23, 24, 25, 26, 27]


marital_status_options = ["Never married(single)", "Married", "Widowed", "Divorced",
"Marital Status unknown"]
marital_status_codes = ["S", "M", "W", "D", "U"]


sex_options = ["Male", "Female"]
sex_codes = ["M", "F"]


race_options = ["Other(Puerto Rico only)", "White", "Black", "American Indian",
"Asian or Pacific Islander"]
race_codes = [0, 1, 2, 3, 4]


hispanic_options = ["Mexican", "Puerto Rican", "Cuban", "Central or South American",
                    "Other or unknown Hispanic",  "Non - Hispanic white", 
                    "Non - Hispanic black", "Non - Hispanic other races", 
                    "Hispanic origin unknown"]
hispanic_codes = [1,2,3,4,5,6,7,8,9]



education_options = ["8th grade or less", "9 - 12th grade, no diploma",
                    "high school graduate or GED", "completed some college credit, but no degree", 
                     "Associate degree", "Bachelor’s degree", "Master’s degree",
                     "Doctorate or professional degree",  "Unknown"]
education_codes = [1,2,3,4,5,6,7,8,9]




print("Age input codes:")
age_input_dictionary = dict(zip(age_group_options, age_group_code))
for age_group_options, age_group_code in age_input_dictionary.items():
    print(age_group_options, "=", age_group_code)
    
print()

print("Marital status input codes:")
marital_status_input_dict = dict(zip(marital_status_options, marital_status_codes))
for marital_status_options, marital_status_codes in marital_status_input_dict.items():
    print(marital_status_options, "=", marital_status_codes)

print()
print("Sex input codes:")
sex_dictionary = dict(zip(sex_options, sex_codes))
for sex_options, sex_codes in sex_dictionary.items():
    print(sex_options, "=", sex_codes)

print()
print("Race input codes:")
race_dictionary = dict(zip(race_options, race_codes))
for race_options, race_codes in race_dictionary.items():
    print(race_options, "=", race_codes)
    
print()
print("Hispanic origin codes:")
hispanic_dictionary = dict(zip(hispanic_options, hispanic_codes))
for hispanic_options, hispanic_codes in hispanic_dictionary.items():
    print(hispanic_options, "=", hispanic_codes)

    
    
print()
print("Education codes:")
education_dictionary = dict(zip(education_options, education_codes))
for education_options, education_codes in education_dictionary.items():
    print(education_options, "=", education_codes) 
    
    


#def input_codes(options, codes):
    #dictionary = dict(zip(options, codes))
    #for options, codes in dictionary.items():
        #print(options, "=", codes)
#input_codes(sex_options, sex_codes)

#question_answer_dictionary = {}

#Question: input()

Age input codes:
Under 1 month = 1
1 month - 11 months = 2
1 year = 3
2 years = 4
3 years = 5
4 years = 6
5  - 9  years = 7
10 - 14 years = 8
15 - 19 years = 9
20 - 24 years = 10
25 - 29 years = 11
30 - 34 years = 12
35 - 39 years = 13
40 - 44 years = 14
45 - 49 years = 15
50 - 54 years = 16
55 - 59 years = 17
60 - 64 years = 18
65 - 69 years = 19
70 - 74 years = 20
75 - 79 years = 21
80 - 84 years = 22
85 - 89 years = 23
90 - 94 years = 24
95 - 99 years = 25

Marital status input codes:
Never married(single) = S
Married = M
Widowed = W
Divorced = D
Marital Status unknown = U

Sex input codes:
Male = M
Female = F

Race input codes:
Other(Puerto Rico only) = 0
White = 1
Black = 2
American Indian = 3
Asian or Pacific Islander = 4

Hispanic origin codes:
Mexican = 1
Puerto Rican = 2
Cuban = 3
Central or South American = 4
Other or unknown Hispanic = 5
Non - Hispanic white = 6
Non - Hispanic black = 7
Non - Hispanic other races = 8
Hispanic origin unknown = 9

Education codes:
8th grade or less = 1
9 - 12th grade, no diploma = 2
high school graduate or GED = 3
completed some college credit, but no degree = 4
Associate degree = 5
Bachelor’s degree = 6
Master’s degree = 7
Doctorate or professional degree = 8
Unknown = 9

In [313]:
now = datetime.datetime.today()

#USER INPUT
user_input = []

for feature in feature_question_list:
    if feature == "What's the current month?":
        user_input.append(now.month)
    elif feature == "What's the day of the week?":
        user_input.append(now.weekday() + 2)
    elif feature == "What's your suicide flag?":
        user_input.append(0)
    else:
        user_input.append(input(feature))



print(user_input)
#user_input_dictionary = dict(zip(input_feature_list, user_input))

What's your sex?F
What's your age?10
What's your marital status?M
What's your race?1
What's your hispanic origin?3
What's your education?5
[2, 'F', '10', 'M', 7, '1', '3', 0, '5']

In [317]:
#json_user_input = json.dumps(user_input_dictionary)
#print(json_user_input)




data = {
  "Inputs": {
    "input1": {
      "ColumnNames": [
        "month_of_death",
        "sex",
        "age_recode_27",
        "marital_status",
        "day_of_week_of_death",
        "race_recode_5",
        "hispanic_origin_race_recode",
        "suicide_flag",
        "education"
      ],
      "Values": [
          user_input
      ]
    }
  },
  "GlobalParameters": {}
}

body = str.encode(json.dumps(data))

# Replace this with the URI and API Key for your web service
url = 'https://ussouthcentral.services.azureml.net/workspaces/f73ee128dfd449ee895acc9220bb073c/services/3af54d474db04806828a1ff21fc142af/execute?api-version=2.0&details=true'
api_key = '5TKRPNg/4VAaoeaicc6qU8s8oer8oH0HmHjaLz3l/uxRKRwTzO6L9azaURcWzt6YzzBSjjuk2xfy+r6tUaIh4Q=='
headers = {'Content-Type':'application/json', 'Authorization':('Bearer '+ api_key)}
#headers = {'Content-Type':'application/json','User-Agent':'cheese'}

# "urllib.request.Request(uri, body, headers)" for Python 3.X
req = urllib.request.Request(url, body, headers)


try:
    response = urllib.request.urlopen(req)

    result = response.read()
    #print(result)
    jsonObject = json.loads(result)
    
    {'Result' : {
        'output1': {
            'type': 'table',
            'value': {
                'ColumnNames': ['month_of_death', 'sex', 'age_recode_27', 'marital_status', 'day_of_week_of_death', 'race_recode_5', 'hispanic_origin_race_recode', 'suicide_flag', 'education', 'Scored Labels', 'Scored Probabilities'],
                'ColumnTypes': ['Int32', 'String', 'Int32', 'String', 'Int32', 'Int32', 'Int32', 'Int64', 'Int64', 'Int64', 'Double'],
                'Values': [
                    ['2', 'F', '10', 'S', '7', '5', '5', '0', '6', '0', '0.140625']
                ]
            }
        }
    }}    
    print("Column names:", jsonObject['Results']['output1']["value"]["ColumnNames"])
    print()
    print("Column types:", jsonObject['Results']['output1']["value"]["ColumnTypes"])
    print()
    print("Values:", jsonObject['Results']['output1']["value"]["Values"])
    
    listOfResults = jsonObject['Results']['output1']["value"]["Values"][0]
    
    for result in listOfResults:
        print(result)


except urllib.error.HTTPError as error:
    print("The request failed with status code: " + str(error.code))
    print(error.info())
    print(json.loads(error.read())) 
    print()
    print(headers)    

# Print the headers - they include the request ID and the timestamp, which are useful for debugging the failure

Column names: ['month_of_death', 'sex', 'age_recode_27', 'marital_status', 'day_of_week_of_death', 'race_recode_5', 'hispanic_origin_race_recode', 'suicide_flag', 'education', 'Scored Labels', 'Scored Probabilities']

Column types: ['Int32', 'String', 'Int32', 'String', 'Int32', 'Int32', 'Int32', 'Int64', 'Int64', 'Int64', 'Double']

Values: [['2', 'F', '10', 'M', '7', '1', '3', '0', '5', '0', '0.25']]
2
F
10
M
7
1
3
0
5
0
0.25